package main

import (
	"bytes"
	"context"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/nicholls-inc/xylem/cli/internal/config"
	"github.com/nicholls-inc/xylem/cli/internal/profiles"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"gopkg.in/yaml.v3"
)

const defaultStateDir = ".xylem"

const scaffoldGitignore = `# Generated by xylem init. Edit to suit your project.
state/
*.lock
!profile.lock
`

const scaffoldConfigHeader = `# xylem configuration
# Docs: https://github.com/nicholls-inc/claude-code-marketplace/tree/main/xylem

`

const scaffoldValidationSample = `
# Sample validation block. Uncomment and replace with your repo's commands.
# validation:
#   format: "goimports -l ."
#   lint:   "go vet ./..."
#   build:  "go build ./..."
#   test:   "go test ./..."
`

type initTemplateData struct {
	Repo     string
	LockedAt string
	Profiles []profiles.Profile
}

func newInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Bootstrap .xylem.yml config and .xylem/ state directory",
		RunE: func(cmd *cobra.Command, args []string) error {
			force, _ := cmd.Flags().GetBool("force")
			profileValue, _ := cmd.Flags().GetString("profile")
			seed, _ := cmd.Flags().GetBool("seed")
			configPath := viper.GetString("config")
			return cmdInitWithProfileAndOptions(configPath, force, profileValue, seed, &realCmdRunner{})
		},
	}
	cmd.Flags().Bool("force", false, "Overwrite existing scaffold files")
	cmd.Flags().String("profile", "core", "Comma-separated profile list (core or core,self-hosting-xylem)")
	cmd.Flags().Bool("seed", false, "Synchronously seed the adapt-repo issue after scaffolding")
	return cmd
}

func cmdInit(configPath string, force bool) error {
	return cmdInitWithProfileAndOptions(configPath, force, "core", false, &realCmdRunner{})
}

func cmdInitWithOptions(configPath string, force, seed bool, runner adaptRepoSeedRunner) error {
	return cmdInitWithProfileAndOptions(configPath, force, "core", seed, runner)
}

func cmdInitWithProfile(configPath string, force bool, profileValue string) error {
	return cmdInitWithProfileAndOptions(configPath, force, profileValue, false, &realCmdRunner{})
}

func cmdInitWithProfileAndOptions(configPath string, force bool, profileValue string, seed bool, runner adaptRepoSeedRunner) error {
	profileNames, err := resolveProfiles(profileValue)
	if err != nil {
		return err
	}

	composed, err := profiles.Compose(profileNames...)
	if err != nil {
		return err
	}

	repo := detectGitHubRepo()
	if repo == "" {
		repo = "owner/name"
	}

	data := initTemplateData{
		Repo:     repo,
		LockedAt: time.Now().UTC().Format(time.RFC3339),
		Profiles: append([]profiles.Profile(nil), composed.Profiles...),
	}

	wroteConfig, err := writeScaffoldConfig(configPath, force, composed, data)
	if err != nil {
		return err
	}
	if wroteConfig {
		fmt.Printf("Created %s\n", configPath)
	} else {
		fmt.Printf("%s already exists (use --force to overwrite)\n", configPath)
	}

	if err := os.MkdirAll(defaultStateDir, 0o755); err != nil {
		return fmt.Errorf("create state directory: %w", err)
	}
	fmt.Printf("Ensured %s/ directory exists\n", defaultStateDir)
	if err := os.MkdirAll(filepath.Join(defaultStateDir, "state"), 0o755); err != nil {
		return fmt.Errorf("create runtime state directory: %w", err)
	}

	gitignorePath := filepath.Join(defaultStateDir, ".gitignore")
	if err := os.WriteFile(gitignorePath, []byte(scaffoldGitignore), 0o644); err != nil {
		return fmt.Errorf("write .gitignore: %w", err)
	}
	fmt.Printf("Created %s\n", gitignorePath)

	harnessContent, err := renderProfileTemplate(composed, "HARNESS.md.tmpl", data)
	if err != nil {
		return err
	}
	if err := writeFileIfNeeded(filepath.Join(defaultStateDir, "HARNESS.md"), []byte(harnessContent), force); err != nil {
		return err
	}

	lockContent, err := renderProfileTemplate(composed, "profile.lock.tmpl", data)
	if err != nil {
		return err
	}
	if err := writeFileIfNeeded(filepath.Join(defaultStateDir, "profile.lock"), []byte(lockContent), force); err != nil {
		return err
	}

	agentsContent, err := renderProfileTemplate(composed, "AGENTS.md.tmpl", data)
	if err != nil {
		return err
	}
	if err := writeAgentsMdIfNeeded("AGENTS.md", []byte(agentsContent), force); err != nil {
		return err
	}

	if err := syncProfileAssets(defaultStateDir, composed, force); err != nil {
		return err
	}

	if seed {
		cfg, err := config.Load(configPath)
		if err != nil {
			return fmt.Errorf("load scaffold config for seeding: %w", err)
		}
		marker, err := ensureAdaptRepoSeeded(context.Background(), cfg, runner, adaptRepoSeededByInit)
		if err != nil {
			return err
		}
		if marker != nil && marker.IssueURL != "" {
			fmt.Printf("Seeded adapt-repo issue: %s\n", marker.IssueURL)
		}
	}

	fmt.Println("\nNext steps:")
	fmt.Printf("  1. Edit %s to confirm your repo, labels, and validation commands\n", configPath)
	fmt.Printf("  2. Edit %s/HARNESS.md with your project details\n", defaultStateDir)
	fmt.Println("  3. Run `xylem scan --dry-run` to preview what would be queued")
	fmt.Println("  4. Run `xylem scan && xylem drain` to start processing")
	return nil
}

func resolveProfiles(raw string) ([]string, error) {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return []string{"core"}, nil
	}

	parts := strings.Split(trimmed, ",")
	names := make([]string, 0, len(parts))
	for _, part := range parts {
		name := strings.TrimSpace(part)
		if name == "" {
			continue
		}
		names = append(names, name)
	}

	switch strings.Join(names, ",") {
	case "core":
		return []string{"core"}, nil
	case "core,self-hosting-xylem":
		return []string{"core", "self-hosting-xylem"}, nil
	default:
		return nil, fmt.Errorf("invalid --profile %q (valid values: core, core,self-hosting-xylem)", raw)
	}
}

func writeFileIfNeeded(path string, content []byte, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			fmt.Printf("skipped: %s (already exists)\n", path)
			return nil
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	fmt.Printf("Created %s\n", path)
	return nil
}

// writeAgentsMdIfNeeded writes content to path with AGENTS.md-specific overwrite semantics:
//   - Without --force: skip if the file already exists.
//   - With --force: overwrite only if the existing file's first line is "# Agents guide";
//     otherwise print a warning and skip (the file is not xylem-managed).
func writeAgentsMdIfNeeded(path string, content []byte, force bool) error {
	if _, err := os.Stat(path); err == nil {
		if !force {
			fmt.Printf("skipped: %s (already exists)\n", path)
			return nil
		}
		existing, readErr := os.ReadFile(path)
		if readErr != nil {
			return fmt.Errorf("read existing %s: %w", path, readErr)
		}
		firstLine := strings.SplitN(string(existing), "\n", 2)[0]
		firstLine = strings.TrimRight(firstLine, "\r")
		if firstLine != "# Agents guide" {
			fmt.Printf("skipped: %s (first line is not '# Agents guide'; edit manually)\n", path)
			return nil
		}
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	fmt.Printf("Created %s\n", path)
	return nil
}

func syncProfileAssets(stateDir string, composed *profiles.ComposedProfile, force bool) error {
	if composed == nil {
		return fmt.Errorf("sync profile assets: composed profile is required")
	}

	for _, name := range sortedKeys(composed.Workflows) {
		if err := writeFileIfNeeded(filepath.Join(stateDir, "workflows", name+".yaml"), composed.Workflows[name], force); err != nil {
			return fmt.Errorf("sync workflow %q: %w", name, err)
		}
	}

	for _, name := range sortedKeys(composed.Prompts) {
		if err := writeFileIfNeeded(filepath.Join(stateDir, "prompts", filepath.FromSlash(name)+".md"), composed.Prompts[name], force); err != nil {
			return fmt.Errorf("sync prompt %q: %w", name, err)
		}
	}

	for _, name := range sortedKeys(composed.Scripts) {
		scriptPath := filepath.Join(stateDir, "scripts", filepath.FromSlash(name))
		if err := writeFileIfNeeded(scriptPath, composed.Scripts[name], force); err != nil {
			return fmt.Errorf("sync script %q: %w", name, err)
		}
		if err := os.Chmod(scriptPath, 0o755); err != nil {
			return fmt.Errorf("chmod script %q: %w", name, err)
		}
	}

	return nil
}

// writeFileForResync writes content to path with profile-authoritative semantics:
//   - If the file does not exist, it is created and "added" is logged.
//   - If the file exists with identical content, it is a no-op.
//   - If the file exists with different content, it is overwritten and "updated" is logged.
//
// This is intentionally authoritative: profile-owned files are always brought
// in sync with the embedded binary. Files not iterated by the caller (daemon-only
// files not present in the composed profile) are never touched.
func writeFileForResync(path string, content []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil {
		if bytes.Equal(existing, content) {
			return nil // already up to date
		}
		// File exists with stale content — overwrite with the embedded version.
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		slog.Info("daemon profile resync: updated file", "path", path)
		return nil
	}
	if !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", path, err)
	}
	// File does not exist — create it.
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	slog.Info("daemon profile resync: added file", "path", path)
	return nil
}

// resyncProfileAssets syncs profile workflows, prompts, and scripts using
// profile-authoritative semantics: existing files with stale content are
// overwritten with the embedded version, and missing files are created.
// Files not iterated (daemon-only files absent from the composed profile)
// are left untouched.
// This is used by the daemon on startup and after each upgrade tick.
func resyncProfileAssets(stateDir string, composed *profiles.ComposedProfile) error {
	if composed == nil {
		return fmt.Errorf("resync profile assets: composed profile is required")
	}

	for _, name := range sortedKeys(composed.Workflows) {
		if err := writeFileForResync(filepath.Join(stateDir, "workflows", name+".yaml"), composed.Workflows[name]); err != nil {
			return fmt.Errorf("resync workflow %q: %w", name, err)
		}
	}

	for _, name := range sortedKeys(composed.Prompts) {
		if err := writeFileForResync(filepath.Join(stateDir, "prompts", filepath.FromSlash(name)+".md"), composed.Prompts[name]); err != nil {
			return fmt.Errorf("resync prompt %q: %w", name, err)
		}
	}

	for _, name := range sortedKeys(composed.Scripts) {
		scriptPath := filepath.Join(stateDir, "scripts", filepath.FromSlash(name))
		if err := writeFileForResync(scriptPath, composed.Scripts[name]); err != nil {
			return fmt.Errorf("resync script %q: %w", name, err)
		}
		if err := os.Chmod(scriptPath, 0o755); err != nil {
			return fmt.Errorf("chmod script %q: %w", name, err)
		}
	}

	return nil
}

func writeScaffoldConfig(configPath string, force bool, composed *profiles.ComposedProfile, data initTemplateData) (bool, error) {
	if !force {
		if _, err := os.Stat(configPath); err == nil {
			return false, nil
		}
	}

	content, err := renderScaffoldConfig(composed, data)
	if err != nil {
		return false, err
	}
	if err := os.WriteFile(configPath, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("write config: %w", err)
	}
	return true, nil
}

func renderScaffoldConfig(composed *profiles.ComposedProfile, data initTemplateData) (string, error) {
	renderedBase, err := renderProfileTemplate(composed, "xylem.yml.tmpl", data)
	if err != nil {
		return "", err
	}

	var doc map[string]any
	if err := yaml.Unmarshal([]byte(renderedBase), &doc); err != nil {
		return "", fmt.Errorf("parse rendered scaffold config: %w", err)
	}

	doc["profiles"] = profileNames(composed.Profiles)

	renderedSources, err := renderSources(composed, data)
	if err != nil {
		return "", err
	}
	doc["sources"] = renderedSources

	daemon, err := renderDaemonOverrides(composed, data)
	if err != nil {
		return "", err
	}
	if len(daemon) > 0 {
		doc["daemon"] = daemon
	}

	body, err := yaml.Marshal(doc)
	if err != nil {
		return "", fmt.Errorf("marshal scaffold config: %w", err)
	}

	return scaffoldConfigHeader + string(body) + scaffoldValidationSample, nil
}

func renderSources(composed *profiles.ComposedProfile, data initTemplateData) (map[string]any, error) {
	rendered := make(map[string]any, len(composed.Sources))
	for _, name := range sortedKeys(composed.Sources) {
		content, err := renderTextTemplate(string(composed.Sources[name]), data)
		if err != nil {
			return nil, fmt.Errorf("render source %q: %w", name, err)
		}
		var src any
		if err := yaml.Unmarshal([]byte(content), &src); err != nil {
			return nil, fmt.Errorf("parse source %q: %w", name, err)
		}
		rendered[name] = src
	}
	return rendered, nil
}

func renderDaemonOverrides(composed *profiles.ComposedProfile, data initTemplateData) (map[string]any, error) {
	daemon := make(map[string]any)
	for _, overlay := range composed.ConfigOverlays {
		var probe map[string]any
		content, err := renderTextTemplate(string(overlay), data)
		if err != nil {
			return nil, fmt.Errorf("render config overlay: %w", err)
		}
		if err := yaml.Unmarshal([]byte(content), &probe); err != nil {
			return nil, fmt.Errorf("parse rendered config overlay: %w", err)
		}
		for key, value := range mapValue(probe["daemon"]) {
			daemon[key] = value
		}
	}
	return daemon, nil
}

func mapValue(value any) map[string]any {
	if value == nil {
		return nil
	}
	if typed, ok := value.(map[string]any); ok {
		return typed
	}
	return nil
}

func profileNames(entries []profiles.Profile) []string {
	names := make([]string, 0, len(entries))
	for _, entry := range entries {
		names = append(names, entry.Name)
	}
	return names
}

func renderProfileTemplate(composed *profiles.ComposedProfile, asset string, data initTemplateData) (string, error) {
	for i := len(composed.Profiles) - 1; i >= 0; i-- {
		content, err := fs.ReadFile(composed.Profiles[i].FS, asset)
		if err == nil {
			rendered, renderErr := renderTextTemplate(string(content), data)
			if renderErr != nil {
				return "", fmt.Errorf("render %s: %w", asset, renderErr)
			}
			return rendered, nil
		}
		if !os.IsNotExist(err) {
			return "", fmt.Errorf("read %s from profile %q: %w", asset, composed.Profiles[i].Name, err)
		}
	}
	return "", fmt.Errorf("render %s: asset not found in composed profiles", asset)
}

func renderTextTemplate(content string, data initTemplateData) (string, error) {
	tmpl, err := template.New("init").Option("missingkey=error").Parse(content)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}
	return buf.String(), nil
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

// parseGitHubRepo extracts "owner/name" from a GitHub remote URL.
// Returns "" for non-GitHub or malformed URLs.
func parseGitHubRepo(remoteURL string) string {
	remoteURL = strings.TrimSpace(remoteURL)
	if remoteURL == "" {
		return ""
	}

	sshRe := regexp.MustCompile(`^git@github\.com:([^/]+/[^/]+?)(?:\.git)?$`)
	if m := sshRe.FindStringSubmatch(remoteURL); m != nil {
		return m[1]
	}

	httpsRe := regexp.MustCompile(`^https://github\.com/([^/]+/[^/]+?)(?:\.git)?$`)
	if m := httpsRe.FindStringSubmatch(remoteURL); m != nil {
		return m[1]
	}

	sshProtoRe := regexp.MustCompile(`^ssh://git@github\.com/([^/]+/[^/]+?)(?:\.git)?$`)
	if m := sshProtoRe.FindStringSubmatch(remoteURL); m != nil {
		return m[1]
	}

	return ""
}

func detectGitHubRepo() string {
	out, err := exec.Command("git", "remote", "get-url", "origin").Output()
	if err != nil {
		return ""
	}
	return parseGitHubRepo(string(out))
}
